// Generated by Skyramp v1.2.23 on 2025-10-31 09:40:55.759737027 -0400 EDT m=+0.689732420
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--playwright-trace skyramp_playwright.zip \

// Import of required libraries
import { test } from '@playwright/test';
import { getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);
    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);

    // wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("https://easyocr-pre-release.digital-ai-app.com/easyocrui/login");
    await page.locator("#mui-7").click();
    const playwrightRequest0: Record<string, any> = {
        "email": "kolja@skyramp.dev",
        "tenantId": "80"
    };

    await page.locator("#mui-7").fill(getValue(playwrightRequest0, "tenantId"));
    await page.locator("#mui-7").press("Tab");
    await page.locator("#mui-5").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#mui-6").click();
    await page.locator("#mui-6").fill("SkyrampTester2025!");
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/easyocrapi/api-easyocr/tenant-preference**");
    await page.getByRole("button", { name: "ログイン" }).click();
    const response0 = await responsePromise0;

    await page.getByRole("button", { name: "件 のファイル（155.1 KB）を開く" }).click();
    await page.locator("button").filter({ hasText: "次へ" }).click();
    await page.locator("button").filter({ hasText: "次へ" }).click();
    await page.locator("button").filter({ hasText: "次へ" }).click();
    await page.locator("button").filter({ hasText: "説明を終了する" }).click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/easyocrapi/api-easyocr/predict/**");
    await page.getByText("範囲を選択").click();
    const response1 = await responsePromise1;

    await page.locator("canvas").click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise2 = page.waitForResponse("**/easyocrapi/api-easyocr/predict/**");
    await page.getByText("範囲を選択").click();
    const response2 = await responsePromise2;

    await page.locator("canvas").click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise3 = page.waitForResponse("**/easyocrapi/api-easyocr/predict/**");
    await page.getByText("範囲を選択").click();
    const response3 = await responsePromise3;

    await page.locator("canvas").click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise4 = page.waitForResponse("**/easyocrapi/api-easyocr/predict/**");
    await page.getByText("範囲を選択").click();
    const response4 = await responsePromise4;

    await page.getByText("1,360").click({ button: "right" });
    await page.getByRole("menuitem", { name: "数字を3桁区切りに変換" }).click();
});
